<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="CmlLib.Core.Installer.NeoForge" Version="4.0.1" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CmlLib.Core.Installer.Forge">
      <HintPath>..\..\CmlLib.Core.Installer.Forge\CmlLib.Core.Installer.Forge\bin\Debug\netstandard2.0\CmlLib.Core.Installer.Forge.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>